version: '3'

services:
  forecast-db: 
    container_name: forecast_database
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=forecastdb
